version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    env_file:
      - ./vars.env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro 
      - ./mongoimport/mongoimport.sh:/docker-entrypoint-initdb.d/mongoimport.sh:ro 
      - ./data/restaurant.json:/restaurant.json:ro 
    ports:
      - '27017:27017'
#
  app:
    container_name: 'app'
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - ./vars.env
    links:
      - mongodb

