version: 2
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
#        environment:
    steps:
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python app.py test

