version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
#        environment:
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox

