apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
### MongoDB container ###
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: pass
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init-mongo.js
          name: init-mongo.js'
          readOnly: true
        - mountPath: /docker-entrypoint-initdb.d/mongoimport.sh
          name: mongoimport-sh
          readOnly: true
        - mountPath: /restaurant.json
          name: restaurant-json
          readOnly: true
### App container ###
      - name: app
        image: app
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: uri
              key: mongo-uri-secret
### Secrets volumes ###
      volumes:
        - name: init-mongo.js
          secret:
            secretName: init-mongo-js
        - name: mongoimport.sh
          secret:
            secretName: mongoimport-sh
        - name: restaurant.json
          secret:
            secretName: restaurant-json
      restartPolicy: Always

